### ISSUE TITLE
Would adding gen:equal+hash to define-type be useful?

### ISSUE THREAD

**Issue by jiujiu1123** [racket/plai#14]
Hi all,

Lately I've come across the need to add custom equality functions to a project dependent on PLAI define-type. While my use case is mainly focused on using free-identifier=? to determine equality amongst PLAI structures, I can see how they could be potentially useful for other use cases. However, I understand that PLAI has a very specific use case for programming languages classes and therefore I am not too sure if adding this will be useful for those situations.

So far I've implemented like this(example inspired by racket docs):
```scheme
(define (farm=? farm1 farm2 recursive-equal?)
  (and (= (farm-apples farm1)
          (farm-apples farm2))
       (= (farm-oranges farm1)
          (farm-oranges farm2))
       (= (farm-sheep farm1)
          (farm-sheep farm2))))
 
(define (farm-hash-code farm recursive-equal-hash)
  (+ (* 10000 (farm-apples farm))
     (* 100 (farm-oranges farm))
     (* 1 (farm-sheep farm))))
 
(define (farm-secondary-hash-code farm recursive-equal-hash)
  (+ (* 10000 (farm-sheep farm))
     (* 100 (farm-apples farm))
     (* 1 (farm-oranges farm))))

(define-type AgriculturalAssets
  [meat-processing ......]
  [farm (apples integer?)
        (oranges integer?)
        (sheep integer?)
        #:equality
        [(define equal-proc farm=?)
         (define hash-proc  farm-hash-code)
         (define hash2-proc farm-secondary-hash-code)]])
```
If this sounds potentially useful, I could put a pull request 😀.

**Comment by rfindler** [comment]
I think this sounds nice. What do you think @jeapostrophe ?

**Comment by jeapostrophe** [comment]
I think this is a "dangerous" road to go down. As you say, `plai` is for PL classes. I could see a case for auto-generating `equal?` implementations, but I can also see that a PL instructor would prefer students to write it themselves to understand issues like alpha-equivalence, rather than representation equality. It's been almost 16 years of `plai` existing without this feature, so I feel it is hard case to make that it is "needed".

I feel that you, and many others, are using `define-type` as a general tool, because disjoint unions and exhaustive matching are so useful. I feel like it would be better to build a library that is for "real Racket" for that purpose and it should expose all of the features of the Racket structures, like properties, using the same notation as `struct`, rather than a new notation, like your `#:equality`.

**Comment by stamourv** [comment]
FWIW, I agree.
And I think keeping PLAI (and its documentation) as simple as we can is probably the right call.

**Comment by rfindler** [comment]
Another approach might be to have a `plai/advanced` library that exports a fancy version of `define-type` with these gizmos and the current `plai` to export a version that just does the syntax checking to make sure the fancy features aren't used and expands into the fancy version.

As a little bit of history here that may be relevant, @jiujiu1123 first started using plai's `define-type` because it was what he knew from taking the PL courses here (thanks, @stamourv !) and so he wanted to make progress on his project without having to slow down to learn some other construct (eg structs and match). He's in a place now where learning those isn't an issue but there is a big pile of code now that would need to be ported. Hence this PR and the request.

So I see that we might consider changes like that with that kind of history in mind. When students decide to use the things they've learned in PLAI for other tasks, maybe it would be helpful to support them with more advanced constructs that they can opt into by simply changing a require line here and there and not making them port their code.

**Comment by shriram** [comment]
I think Robby's idea is a good one. Students get into Racket through plai
or plait or whatever, so that's all they know, and it's the only ML-typed
language in the ecosystem, so TR is not necessarily a good alternative. At
the same time, keeping plai as simple as possible and as suited to teaching
PL as possible is really important. A plai/advanced that exposes more of
Racket and enables more "real programming" would be a great way to have
both things.

**Comment by jiujiu1123** [comment]
I think given the response, it's best to keep PLAI as it is, especially given its status as a teaching language. Thank y'all for the feedback. I think I particularly like @jeapostrophe 's idea about repackaging part of PLAi's define-type infrastructure as a seperate package for general racket, just feels quite neat. I might look into that.
