### ISSUE TITLE
missing roots in gc2 example

### ISSUE THREAD

**Issue by bremner** [racket/plai#15]
I apologize in advance for the lack of a small reproducer, and confess to some uncertainty as to whether this is a bug report or a support request.
I have tested the attached examples with 7.9 [bc] and 8.0 [cs]

I have a simple mark and sweep collector in gc2 that I inherited from somewhere (quite possibly from Vincent). I also have a simple quicksort implementation to exercise the collector. At some point I see a collection where the heap does not contain any references to location 245, and neither is it passed in as a root. Sure enough, location 245 is freed. The mutator then tries to run first on that location and crashes.

I concede it's just as likely I've misunderstood something, but I thought that maintaining the root set was up to the mutator language. There is the passing around of extra roots in the collector, but have at least attempted to test that.

[debug.rkt.gz](https://github.com/racket/plai/files/6299838/debug.rkt.gz)
[sort.rkt.gz](https://github.com/racket/plai/files/6299841/sort.rkt.gz)

**Comment by jeapostrophe** [comment]
I did some spelunking by inserting lots of print-outs. You're in a `reverse` and trying to allocate the `empty` first argument and that's when the `gc:flat` calls `collect`. That `l` is the 245 that isn't tracked, because the mutator expander is treating identifier macros as if they were normal macros. `empty` is an identifier macro, so that's why that `(gc:flat '())` didn't see the `l`. This was a real error in the mutator transformer. Good job finding this one! I pushed a fix.

**Comment by bremner** [comment]
Jay McCarthy ***@***.***> writes:

> I did some spelunking by inserting lots of print-outs. You're in a
> `reverse` and trying to allocate the `empty` first argument and that's
> when the `gc:flat` calls `collect`. That `l` is the 245 that isn't
> tracked, because the mutator expander is treating identifier macros as
> if they were normal macros. `empty` is an identifier macro, so that's
> why that `(gc:flat '())` didn't see the `l`. This was a real error in
> the mutator transformer. Good job finding this one! I pushed a fix.

Thanks for the fix, impressive debugging chops!

d
